#!/bin/sh -e

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddebug=false \
    -Djpeg=enabled \
    -Dpng=enabled \
    -Dtiff=disabled \
    -Dgtk_doc=false \
    -Dman=false \
    -Dgio_sniffing=false \
    -Dtests=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    -Dwrap_mode=nofallback \
    . output

ninja -C output
ninja -C output install
