#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -fPIC"

# Build fails with clang due to -Werror (forced on) and
# -Wunused-command-line-argument which is triggered by.
# the below CFLAGS.
export CFLAGS="-Wno-unused-command-line-argument $CFLAGS"

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlibexecdir=/usr/lib \
    -Ddefault_library=both \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    output

ninja -C output
ninja -C output install
