#!/bin/sh -e

muon setup \
    -Dprefix=/usr \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Drenderers=gles2 \
    build

ninja -C build
muon  -C build install
