#!/bin/sh -e

unzip ./*.zip

cd "wlroots-eglstreams-$2"

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Dx11-backend=disabled \
    . build

ninja -C build
ninja -C build install
