#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -I$PWD/eglexternalplatform/interface"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$PWD/eglexternalplatform"

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install

mkdir -p "$1/usr/share/egl/egl_external_platform.d/"
cp 10_nvidia_wayland.json "$1/usr/share/egl/egl_external_platform.d/"
