#!/bin/sh

[ "$(whoami)" = root ] || {
    echo "Please run as root"
    exit 1
}

[ -r /etc/locale.gen ] || {
    echo "Cannot open /etc/locale.gen for reading"
    exit 1
}

while read -r line; do
    INPUTFILE="${line%% *}"
    INPUTFILE="${INPUTFILE%%.*}"
    CHARMAPFILE="${line##* }"
    echo "Generating locale $INPUTFILE.$CHARMAPFILE"
    localedef -i "$INPUTFILE" -f "$CHARMAPFILE" "$INPUTFILE.$CHARMAPFILE" || {
        echo "Generating locale $INPUTFILE.$CHARMAPFILE failed"
        exit 1
    }
done < /etc/locale.gen
