#!/bin/sh -e

patch -p1 < add-av_stream_get_first_dts-for-chromium.patch

./configure \
    --cc="$CC" \
    --cxx="$CXX" \
    --prefix=/usr \
    --disable-debug \
    --disable-libxml2 \
    --disable-static \
    --disable-libxcb \
    --disable-libxcb-shm \
    --disable-libxcb-xfixes \
    --disable-libxcb-shape \
    --disable-xlib \
    --enable-gpl \
    --enable-libass \
    --enable-libdrm \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-nonfree \
    --enable-openssl \
    --enable-shared \
    --enable-version3 \
    --enable-nvdec \
    --enable-nvenc \
    --x86asmexe=nasm

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/ffmpeg/examples"
