#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-vulkan-headers.patch

meson setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dvulkan=disabled \
    -Ddemos=false \
    output

ninja -C output
ninja -C output install
