#!/bin/sh -e

patch -p1 < no-evdev.patch

# Default background color.
sed 's/0.25f, 0.25f, 0.25f/0.929, 0.870, 0.678/' \
    sway/desktop/render.c > _
mv -f _ sway/desktop/render.c

export DESTDIR="$1"
export CFLAGS="$CFLAGS -Wno-error"

meson \
    --prefix=/usr \
    -Ddefault-wallpaper=false \
    -Dzsh-completions=false \
    -Dbash-completions=false \
    -Dfish-completions=false \
    . build

ninja -C build
ninja -C build install
