#!/bin/sh -e

version=450.80.02

sh NVIDIA-Linux-x86_64-$version.run --extract-only
cd NVIDIA-Linux-x86_64-$version

# X driver
install -d "$1/usr/lib/xorg/modules/drivers"
install -m755 nvidia_drv.so "$1/usr/lib/xorg/modules/drivers/"

# GLX extension module for X
install -dm755 "$1/usr/lib/nvidia/xorg"
install -m755 libglxserver_nvidia.so.$version "$1/usr/lib/nvidia/xorg/"
# Ensure that X find GLX
ln -s libglxserver_nvidia.so.$version "$1/usr/lib/nvidia/xorg/libglxserver_nvidia.so"
ln -s libglxserver_nvidia.so.$version "$1/usr/lib/nvidia/xorg/libglxserver_nvidia.so.1"

# GLVND libraries
install -m755 libGLX_nvidia.so.$version "$1/usr/lib/"
install -m755 libEGL_nvidia.so.$version "$1/usr/lib/"
ln -s libGLX_nvidia.so.$version         "$1/usr/lib/libGLX_nvidia.so.0"
ln -s libEGL_nvidia.so.$version         "$1/usr/lib/libEGL_nvidia.so.0"

# OpenGL ES libraries
install -d "$1/usr/lib"
install -m755 libGLESv1_CM_nvidia.so.$version "$1/usr/lib/"
install -m755 libGLESv2_nvidia.so.$version    "$1/usr/lib/"
ln -s libGLESv1_CM_nvidia.so.$version "$1/usr/lib/libGLESv1_CM_nvidia.so.1"
ln -s libGLESv2_nvidia.so.$version    "$1/usr/lib/libGLESv2_nvidia.so.2"
install -Dm644 10_nvidia.json "$1/usr/share/glvnd/egl_vendor.d/10_nvidia.json"

# Vulkan ICD
install -d "$1/etc/vulkan/icd.d"
install -m644 nvidia_icd.json "$1/etc/vulkan/icd.d/"

# Driver component libraries
install -m755 libnvidia-cfg.so.$version       "$1/usr/lib/"
install -m755 libnvidia-compiler.so.$version  "$1/usr/lib/"
install -m755 libnvidia-eglcore.so.$version   "$1/usr/lib/"
install -m755 libnvidia-glcore.so.$version    "$1/usr/lib/"
install -m755 libnvidia-glsi.so.$version      "$1/usr/lib/"
install -m755 libnvidia-glvkspirv.so.$version "$1/usr/lib/"
install -m755 libnvidia-rtcore.so.$version    "$1/usr/lib/"
install -m755 libnvidia-cbl.so.$version       "$1/usr/lib/"

# VDPAU library
install -Dm755 libvdpau_nvidia.so.$version "$1/usr/lib/vdpau/libvdpau_nvidia.so.$version"
ln -s libvdpau_nvidia.so.$version "$1/usr/lib/vdpau/libvdpau_nvidia.so.1"
ln -s libvdpau_nvidia.so.$version "$1/usr/lib/vdpau/libvdpau_nvidia.so"

# CUDA libraries
install -m755 libcuda.so.$version "$1/usr/lib/"
install -m755 libnvidia-ptxjitcompiler.so.$version "$1/usr/lib/"
ln -s libcuda.so.$version "$1/usr/lib/libcuda.so"
ln -s libcuda.so.$version "$1/usr/lib/libcuda.so.1"
ln -s libnvidia-ptxjitcompiler.so.$version "$1/usr/lib/libnvidia-ptxjitcompiler.so"
ln -s libnvidia-ptxjitcompiler.so.$version "$1/usr/lib/libnvidia-ptxjitcompiler.so.1"

# OpenCL libraries
install -m755 libOpenCL.so.1.0.0           "$1/usr/lib/"
install -m755 libnvidia-opencl.so.$version "$1/usr/lib/"
install -Dm644 nvidia.icd "$1/etc/OpenCL/vendors/nvidia.icd"
ln -s libnvidia-opencl.so.$version "$1/usr/lib/libnvidia-opencl.so"
ln -s libnvidia-opencl.so.$version "$1/usr/lib/libnvidia-opencl.so.1"

# CUDA MPI applications
install -d "$1/usr/bin"
install -m755 nvidia-cuda-mps-control "$1/usr/bin/"
install -m755 nvidia-cuda-mps-server  "$1/usr/bin/"

# TLS library
install -m755 libnvidia-tls.so.$version "$1/usr/lib/"

# Monitoring and management API library
install -m755 libnvidia-ml.so.$version "$1/usr/lib/"

# Applications
install -m4755 nvidia-modprobe "$1/usr/bin/"
for bin in persistenced settings smi xconfig; do
    install -m755 nvidia-$bin "$1/usr/bin"
done

# nvidia-settings UI library
install -m755 libnvidia-gtk3.so.$version "$1/usr/lib/"

# Encoding/decoding libraries
install -m755 libnvcuvid.so.$version       "$1/usr/lib/"
install -m755 libnvidia-encode.so.$version "$1/usr/lib/"
install -m755 libnvidia-ifr.so.$version    "$1/usr/lib/"
install -m755 libnvidia-fbc.so.$version    "$1/usr/lib/"

# OptiX ray tracing engine
install -m755 libnvoptix.so.$version "$1/usr/lib/"
ln -s libnvoptix.so.$version "$1/usr/lib/libnvoptix.so"
ln -s libnvoptix.so.$version "$1/usr/lib/libnvoptix.so.1"

# Optical Flow library
install -m755 libnvidia-opticalflow.so.$version "$1/usr/lib/"
ln -s libnvidia-opticalflow.so.$version "$1/usr/lib/libnvidia-opticalflow.so"
ln -s libnvidia-opticalflow.so.$version "$1/usr/lib/libnvidia-opticalflow.so.1"

# NGX library
install -m755 libnvidia-ngx.so.$version "$1/usr/lib/"
ln -s libnvidia-ngx.so.$version "$1/usr/lib/libnvidia-ngx.so"
ln -s libnvidia-ngx.so.$version "$1/usr/lib/libnvidia-ngx.so.1"

# Application profiles
install -dm755 "$1/usr/share/nvidia"
install -m644 nvidia-application-profiles-$version-rc \
    "$1/usr/share/nvidia/"
install -m644 nvidia-application-profiles-$version-key-documentation \
    "$1/usr/share/nvidia/"

# Kernel modules
cd kernel
make module
install -d "$1/lib/modules/$(uname -r)/extra"
install -m644 ./*.ko "$1/lib/modules/$(uname -r)/extra/"
