#!/bin/sh

/usr/bin/depmod "${KERNEL_UNAME:-$(uname -r)}"
/usr/bin/ldconfig

cat <<EOF

NOTE: Run 'nvidia-xconfig' to generate an X configuration file.
NOTE: The 'nvidia' package must be rebuilt after each kernel update.

EOF
