#!/bin/sh -e

# Setup docutils to generate manual pages.
{
    cd docutils

    python3 setup.py build
    python3 setup.py install \
        --root="$PWD/../dist"

    cd ../dist/usr/lib/python*/site-packages

    PYTHONPATH=$PWD:$(python -c "import sys;print(':'.join(sys.path))")

    cd -; cd ..
    export PATH=$PWD/dist/usr/bin:$PATH
    export PYTHONPATH
}

muon setup \
    -Dprefix=/usr \
    -Dalsa=enabled \
    -Dlibmpv=true \
    -Dwayland=enabled \
    -Dx11=disabled \
    output

ninja -C output
muon  -C output install

rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion"
