#!/bin/sh -e

export DESTDIR="$1"

: > fuzzing/meson.build

meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    -Dlibmount=disabled \
    -Dinstalled_tests=false \
    -Ddefault_library=both \
    -Dman=false \
    -Dtests=false \
    -Dlibelf=disabled \
    -Dnls=disabled \
    -Dsysprof=disabled \
    build

ninja -C build
ninja -C build install

rm -rf "$1/usr/bin/gdbus"
