#!/bin/sh -e

export DESTDIR="$1"

: > fuzzing/meson.build

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Dlibmount=disabled \
    -Dinstalled_tests=false \
    -Ddefault_library=both \
    -Dman=false \
    -Dtests=false \
    -Dlibelf=disabled \
    -Dnls=disabled \
    . build

ninja -C build
ninja -C build install

rm -rf "$1/usr/bin/gdbus"
