#!/bin/sh -e

sed 's/VERSION 2.8/VERSION 3.9...3.12/' apps/CMakeLists.txt > _
mv -f _ apps/CMakeLists.txt

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DDISABLE_EXTRA_LIBS=ON \
    -DBUILD_TESTING=OFF

cmake --build   build
cmake --install build
