#!/bin/sh -e

export DESTDIR="$1"

# rust_std is not (yet?) supported by muon, and we should try
# to avoid a hard rust dependency here if possible.
sed "s/, 'rust_std=2021'//" meson.build > _
mv -f _ meson.build

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
pkg-config --exists libglvnd || glvnd_enabled=false

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=wayland \
    -Dglx=disabled \
    -Degl=enabled \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dglvnd="${glvnd_enabled:-true}" \
    -Dvulkan-drivers='' \
    . output

ninja -C output
ninja -C output install
