#!/bin/sh -e

export DESTDIR="$1"

cd libclc
cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DLIBCLC_TARGETS_TO_BUILD=''

cmake --build   build
cmake --install build
