#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-static \
    --disable-tiff \
    --enable-libwebpmux \
    --enable-libwebpdemux \
    --enable-libwebpdecoder

make
make DESTDIR="$1" install
