#!/bin/sh -e

./configure \
    --prefix=/usr

make

make -C lib     DESTDIR="$1" install
make -C include DESTDIR="$1" install

make DESTDIR="$1" \
    install-m4dataDATA \
    install-pkgconfigDATA

