#!/bin/sh -e

patch -p1 -R < 0001-Fixed-OpenGL-ES-Shaders-for-systems-that-don-t-under.patch

./configure \
    --disable-video-opengl \
    --enable-video-opengles \
    --disable-rpath \
    --prefix=/usr

make
make DESTDIR="$1" install
