#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-doc \
    --disable-nls

make
make install

# Link the binaries statically
cd src
rm -f xz/xz lzmainfo/lzmainfo xzdec/lzmadec xzdec/xzdec

make LDFLAGS="$LDFLAGS -all-static" -C xz
make LDFLAGS="$LDFLAGS -all-static" -C lzmainfo
make LDFLAGS="$LDFLAGS -all-static" -C xzdec

for bin in xz/xz lzmainfo/lzmainfo xzdec/lzmadec xzdec/xzdec; do
    cp "$bin" "$DESTDIR/usr/bin"
    chmod 755 "$DESTDIR/usr/bin/${bin##*/}"
done
