#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dime=false \
    -Dwerror=false \
    output

ninja -C output
ninja -C output install

rm -rf \
    "$1/usr/share/doc" \
    "$1/usr/share/zsh" \
    "$1/usr/share/fish" \
    "$1/usr/share/bash-completion"
