#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
sed -i "/subdir('tests')/d" meson.build

x11=disabled
kiss list xorg-server && x11=enabled

meson \
    --prefix=/usr \
    -Dx11="$x11" \
    . output

ninja -C output
ninja -C output install
