#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
sed -i "/subdir('tests')/d" meson.build

meson \
    --prefix=/usr \
    -Dx11=disabled \
    . output

ninja -C output
ninja -C output install
