#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dwith_wayland=yes \
    -Dwith_x11=no \
    -Dwith_glx=no \
    output

ninja -C output
ninja -C output install
