#!/bin/sh -e

# Build cannot happen without optimizations.
CFLAGS="${CFLAGS:--Os}"

# Build must happen outside of glibc source.
mkdir -p glibc-build
cd glibc-build

../configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --libexecdir=/usr/lib \
    --disable-werror

printf '%s\n' \
    "slibdir=/usr/lib" \
    "rtlddir=/usr/lib" \
    "sbindir=/usr/bin" \
    "rootsbindir=/usr/bin" > configparms

make
make DESTDIR="$1" install

rm  "$1/var/db/Makefile" \
    "$1/usr/bin/ldd" \
    "$1/usr/bin/sotruss" \
    "$1/usr/bin/xtrace" \
    "$1/usr/bin/tzselect"

# Setup locale directory.
install -dm 755 "$1/usr/lib/locale"

# Install locale script for generating locales.
:> "$1/etc/locale.gen"
install -Dm755 ../locale-gen "$1/usr/bin/locale-gen"

# Replace bash scripts with POSIX sh ports.
install -Dm755 ../ldd     "$1/usr/bin/ldd"
install -Dm755 ../sotruss "$1/usr/bin/sotruss"
