#!/bin/sh -e

# Build cannot happen without optimizations.
CFLAGS="${CFLAGS:--Os}"

# Build must happen outside of glibc source.
mkdir -p glibc-build
cd glibc-build

../configure \
    --prefix=/usr \
    --disable-werror

make
make DESTDIR="$1" install

rm  "$1/var/db/Makefile" \
    "$1/usr/bin/ldd" \
    "$1/usr/bin/sotruss" \
    "$1/usr/bin/xtrace"

# Setup locale directory.
install -dm 755 "$1/usr/lib/locale"

# Install locale script for generating locales.
install -Dm755 ../locale-gen "$1/usr/bin/locale-gen"
install -Dm644 ../locale.gen "$1/etc/locale.gen"

# Replace bash scripts with POSIX sh ports.
install -Dm755 ../ldd     "$1/usr/bin/ldd"
install -Dm755 ../sotruss "$1/usr/bin/sotruss"
