#!/bin/sh -e

patch -p1 < no-gperf.patch

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dxml-dir=/etc/fonts \
    -Ddoc=disabled \
    -Dnls=disabled \
    output

ninja -C output
ninja -C output install
