#!/bin/sh -e

export CFLAGS="$CFLAGS -std=gnu17"

./configure \
    --prefix=/usr

make
make -C lib     DESTDIR="$1" install
make -C include DESTDIR="$1" install
make            DESTDIR="$1" install-pkgconfigDATA
