#!/bin/sh -e

patch -p1 < nvidia-format.patch

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Drenderers=gles2 \
    . build

ninja -C build
ninja -C build install
