#!/bin/sh -e

export DESTDIR="$1"

for p in *.patch; do
    patch -p1 < "$p"
done

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Drenderers=gles2 \
    . build

ninja -C build
ninja -C build install
