#!/bin/sh -e

case "$TYPE" in
    pre-build)
        export _CC="${CC:-cc}"
        export _CXX="${CXX:-c++}"
        export _PKG_CONFIG_PATH="$PKG_CONFIG_PATH"

        case "$PKG" in
            lib32-*)
                export CC="gcc -m32"
                export CXX="g++ -m32"
                export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
            ;;
        esac
    ;;

    post-build)
        : "${DEST:?DEST is unset}"

        export CC="$_CC"
        export CXX="$_CXX"
        export PKG_CONFIG_PATH="$_PKG_CONFIG_PATH"

        case "$PKG" in
            lib32-glibc) ;;
            lib32-*)
                rm -rf "$3/etc" \
                       "$3/usr/bin" \
                       "$3/usr/include" \
                       "$3/usr/share"
            ;;
        esac

        # Default package manager hook.
        rm -rf "$3/usr/share/gettext" \
               "$3/usr/share/polkit-1" \
               "$3/usr/share/locale" \
               "$3/usr/share/info"
    ;;
esac
