#!/bin/sh -e

patch -p1 < musl.patch

# Build sometimes forces -Werror.
export CFLAGS="$CFLAGS -Wno-error"

sh ./configure \
    --prefix=/usr \
    --disable-symbol-versioning \
    --disable-debuginfod \
    --disable-libdebuginfod \
    --disable-nls \
    ac_cv_c99=yes # Override check for Clang.

# Skip the default make target and build only what we need.
make -C lib
make -C libelf
make -C libelf DESTDIR="$1" install
make -C doc    DESTDIR="$1" install-man3

mkdir -p "$1/usr/lib/pkgconfig"
cp -f config/libelf.pc "$1/usr/lib/pkgconfig/libelf.pc"
