#!/bin/sh -e

version=465.24.02

sh NVIDIA-Linux-x86_64-$version.run --extract-only
cd NVIDIA-Linux-x86_64-$version

cd 32

install -Dm755 "libGLX_nvidia.so.$version" "$1/usr/lib32/libGLX_nvidia.so.$version"

# OpenGL libraries
install -Dm755 "libEGL_nvidia.so.$version"       "$1/usr/lib32/libEGL_nvidia.so.$version"
install -Dm755 "libGLESv1_CM_nvidia.so.$version" "$1/usr/lib32/libGLESv1_CM_nvidia.so.$version"
install -Dm755 "libGLESv2_nvidia.so.$version"    "$1/usr/lib32/libGLESv2_nvidia.so.$version"

# OpenGL core library
install -Dm755 "libnvidia-glcore.so.$version"  "$1/usr/lib32/libnvidia-glcore.so.$version"
install -Dm755 "libnvidia-eglcore.so.$version" "$1/usr/lib32/libnvidia-eglcore.so.$version"
install -Dm755 "libnvidia-glsi.so.$version"    "$1/usr/lib32/libnvidia-glsi.so.$version"

# misc
install -Dm755 "libnvidia-ifr.so.$version"       "$1/usr/lib32/libnvidia-ifr.so.$version"
install -Dm755 "libnvidia-fbc.so.$version"       "$1/usr/lib32/libnvidia-fbc.so.$version"
install -Dm755 "libnvidia-encode.so.$version"    "$1/usr/lib32/libnvidia-encode.so.$version"
install -Dm755 "libnvidia-ml.so.$version"        "$1/usr/lib32/libnvidia-ml.so.$version"
install -Dm755 "libnvidia-glvkspirv.so.$version" "$1/usr/lib32/libnvidia-glvkspirv.so.$version"

# VDPAU
install -Dm755 "libvdpau_nvidia.so.$version" "$1/usr/lib32/vdpau/libvdpau_nvidia.so.$version"

ln -s "libvdpau_nvidia.so.$version" "$1/usr/lib32/vdpau/libvdpau_nvidia.so.1"
ln -s "libvdpau_nvidia.so.$version" "$1/usr/lib32/vdpau/libvdpau_nvidia.so"

# nvidia-tls library
install -Dm755 "libnvidia-tls.so.$version" "$1/usr/lib32/libnvidia-tls.so.$version"

# CUDA
install -Dm755 "libcuda.so.$version"    "$1/usr/lib32/libcuda.so.$version"
install -Dm755 "libnvcuvid.so.$version" "$1/usr/lib32/libnvcuvid.so.$version"

# PTX JIT Compiler (Parallel Thread Execution (PTX) is a pseudo-assembly language for CUDA)
install -Dm755 "libnvidia-ptxjitcompiler.so.$version" "$1/usr/lib32/libnvidia-ptxjitcompiler.so.$version"

# Optical flow
install -Dm755 "libnvidia-opticalflow.so.$version" "$1/usr/lib32/libnvidia-opticalflow.so.$version"

# soname links
for lib in "$1/usr/lib32/"*.so*; do
    soname=$(dirname "$lib")/$(readelf -d "$lib" | awk '/SONAME/ { print $5 }' | tr -d '[]')
    base=$(echo "$soname" | sed -r 's/(.*).so.*/\1.so/')
    [ -e "$soname" ] || ln -s "$(basename "$lib")" "$soname"
    [ -e "$base" ] || ln -s "$(basename "$soname")" "$base"
done
