#!/bin/sh -e

# Use lib not lib64 by default.
sed '/m64=/s/lib64/lib/' gcc/config/i386/t-linux64 > _
mv -f _ gcc/config/i386/t-linux64
sed 's/lib64/lib/' gcc/config/i386/linux64.h > _
mv -f _ gcc/config/i386/linux64.h

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

# Grab the system's GCC version.
gcc_version=$(gcc -dumpfullversion 2>/dev/null) || gcc_version=null

# Skip the bootstrap process if we are able.
case $2 in "${gcc_version%%.*}"*)
    printf '%s\n' "Minor version difference, disabling bootstrap."
    bootstrap=--disable-bootstrap
esac

../configure \
    libat_cv_have_ifunc=no \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-multilib \
    --disable-libmpx \
    --disable-libmudflap \
    --disable-libsanitizer \
    --disable-werror \
    --disable-fixed-point \
    --disable-libstdcxx-pch \
    --disable-nls \
    --enable-checking=release \
    --enable-__cxa_atexit \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-shared \
    --enable-threads \
    --enable-tls \
    --enable-initfini-array \
    --enable-languages=c,c++ \
    --without-included-gettext \
    --with-zstd=no \
    --with-system-zlib \
    --build=x86_64-pc-linux-gnu \
    "${bootstrap:---enable-bootstrap}"

make
make DESTDIR="$1" install

# Save 35MB.
find "$1" -name libgtkpeer.a  -exec rm -f {} +
find "$1" -name libgjsmalsa.a -exec rm -f {} +
find "$1" -name libgij.a      -exec rm -f {} +

ln -sf gcc "$1/usr/bin/cc"
cp -f ../c99 "$1/usr/bin"

# Symlink for LTO.
{
    mkdir -p "$1/usr/lib/bfd-plugins"

    ln -s "/usr/lib/gcc/x86_64-pc-linux-gnu/$2/liblto_plugin.so" \
          "$1/usr/lib/bfd-plugins/liblto_plugin.so"
}
