#!/bin/sh -e

# Build fails in with clang due to
# -Werror -> -Wsign-compare.
export CFLAGS="-Wno-error $CFLAGS"
export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Ddefault_library=both \
    build

ninja -C build
ninja -C build install

# Set suid on seatd-launch.
chmod u+s "$1/usr/bin/seatd-launch"

# Install runit service.
mkdir -p "$1/etc/sv/seatd"
cp -f seatd.run "$1/etc/sv/seatd/run"
ln -sf /run/runit/supervise.seatd "$1/etc/sv/seatd/supervise"
